window.dnd_cc = typeof window.dnd_cc === "undefined" ? {} : window.dnd_cc;

console.log("setting manifest");

window.dnd_cc.MANIFEST = {
  // ARMOR START
  "leather armor" : 10 ,
  "studded leather armor" : 13 ,
  "hide armor" : 12 ,
  "chain shirt" : 20 ,
  "scale mail" : 45 ,
  "breastplate" : 20 ,
  "ring mail" : 40 ,
  "chain mail" : 55 ,
  "spint" : 60 ,
  "shield" : 6 ,
  // ARMOR END
  //WEAPONS
  "club" : 2 ,
  "dagger" : 1 ,
  "greatclub" : 10 ,
  "handaxe" : 2 ,
  "javelin" : 2 ,
  "light hammer" : 2 ,
  "mace" : 4 ,
  "quarterstaff" : 4 ,
  "spear" : 3 ,
  "light crossbow" : 5 ,
  "shortbow" : 2 ,
  "battleaxe" : 4 ,
  "greataxe" : 7 ,
  "greatsword" : 6 ,
  "longsword" : 3 ,
  "maul" : 10 ,
  "morningstar" : 4 ,
  "rapier" : 2 ,
  "scimitar" : 3 ,
  "shortsword" : 2 ,
  "trident" : 4 ,
  "warhammer" : 2 ,
  "hand crossbow" : 3 ,
  "heavy crossbow" : 18 ,
  "longbow" : 2 ,
  // END WEAPONS
  // START GEAR
  "arrows" : 0.05 ,
  "crossbow bolts" : 0.075 ,
  "backpack" : 5 ,
  "bedroll" : 7 ,
  "bell" : 0 ,
  "blanket" : 3 ,
  "book" : 5 ,
  "candle" : 0 ,
  "carpenter's tools" : 6 ,
  "scroll case" : 1 ,
  "chalk" : 0,
  "chest" : 25 ,
  "common clothes" : 3 ,
  "fine clothes" : 6 ,
  "component pouch" : 2 ,
  "grappling hook" : 4 ,
  "hammer" : 3 ,
  "sledge hammer" : 10 ,
  "healer's kit" : 3 ,
  "holy symbol" : 1 ,
  "hourglass" : 1 ,
  "ink bottle" : 0,
  "ink pen": 0,
  "lantern" : 2 ,
  "lock" : 1 ,
  "mason's tools" : 8 ,
  "mess kit" : 1 ,
  "steel mirror" : 0.5 ,
  "oil flask" : 1 ,
  "sheet of paper" : 0,
  "sheet of parchment" : 0,
  "perfume vial" : 0,
  "miner's pick" : 10 ,
  "piton" : 0.25 ,
  "iron pot" : 10 ,
  "potion of healing" : 0.5 ,
  "playing cards" : 0,
  "pouch" : 1 ,
  "rations" : 2 ,
  "robes" : 4 ,
  "hempen rope 50 ft" : 10 ,
  "silk rope" : 5 ,
  "sack" : 0.5 ,
  "sealing wax" : 0,
  "shovel" : 5 ,
  "signal whistle" : 0,
  "signet ring" : 0,
  "spellbook" : 3 ,
  "iron spike" : 0.5 ,
  "tent two-person" : 20 ,
  "thief's tools" : 1 ,
  "tinderbox" : 1 ,
  "torch" : 1 ,
  "waterskin full" : 5 ,
  "whetstone" : 1
  // END GEAR
}
